const CONFIG={
  petalPhrases:['Porque contigo todo se siente más bonito.','Porque me encanta compartir mis días contigo.','Porque siempre encuentras la forma de hacerme sonreír.','Porque te mereces algo hecho con calma y cariño.','Porque eres una persona muy especial para mí.','Porque hasta los momentos sencillos se sienten diferentes contigo.','Porque quería recordarte lo mucho que te quiero.','Porque esta flor es pequeña, pero lo que siento no.'],
  storyTimeline:['Antes de conocerte, no imaginaba que alguien pudiera volverse tan importante para mí.','Después apareciste tú y mis días empezaron a tener conversaciones que esperaba con ilusión.','Sin darme cuenta, tus detalles se convirtieron en mis momentos favoritos.','Por eso hice esta flor: para regalarte algo tan bonito como lo que me haces sentir.','Gracias por existir y por hacer un espacio tan especial en mi vida, Poncho.']
};
const $=s=>document.querySelector(s);const screens={intro:$('#screen-intro'),game:$('#screen-game'),completed:$('#screen-completed'),story:$('#screen-story'),outro:$('#screen-outro')};
function go(from,to){from.classList.remove('active');setTimeout(()=>to.classList.add('active'),180)}
for(let i=0;i<18;i++){const d=document.createElement('i');d.className='dust';d.style.left=Math.random()*100+'%';d.style.animationDelay=Math.random()*8+'s';$('#ambient').append(d)}
$('#btn-start').addEventListener('click',()=>{go(screens.intro,screens.game);initGame()});
let placed=0,total=8,phraseIndex=0,gameReady=false;
function initGame(){if(gameReady)return;gameReady=true;const board=$('#game-board'),targetBox=$('#targets'),petalBox=$('#petals-container');
 const center=()=>({x:board.clientWidth/2,y:Math.min(160,board.clientHeight*.35)});const angles=[-90,-45,0,45,90,135,180,225];
 function paintTargets(){const c=center();targetBox.innerHTML='';angles.forEach((a,i)=>{const r=a*Math.PI/180,t=document.createElement('div');t.className='target';t.dataset.i=i;t.style.left=c.x+Math.cos(r)*83+'px';t.style.top=c.y+Math.sin(r)*83+'px';t.style.transform=`translate(-50%,-50%) rotate(${a+90}deg)`;targetBox.append(t)})}
 paintTargets();window.addEventListener('resize',paintTargets);
 for(let i=0;i<total;i++){const p=document.createElement('button');p.className='petal';p.setAttribute('aria-label','Pétalo '+(i+1));const col=i%4,row=Math.floor(i/4);p.style.left=(12+col*23+Math.random()*7)+'%';p.style.top=(70+row*14)+'%';p.style.transform=`rotate(${[-18,8,25,-12,14,-20,7,18][i]}deg)`;petalBox.append(p);drag(p)}
 function drag(p){let active=false,origin={x:0,y:0};p.addEventListener('pointerdown',e=>{if(p.classList.contains('placed'))return;active=true;p.setPointerCapture(e.pointerId);p.classList.add('dragging');const r=p.getBoundingClientRect();origin={x:r.left+r.width/2,y:r.top+r.height/2};p.style.position='fixed';p.style.left=origin.x-r.width/2+'px';p.style.top=origin.y-r.height/2+'px';p.style.transform='rotate(0deg)'})
 p.addEventListener('pointermove',e=>{if(!active)return;p.style.left=e.clientX-p.offsetWidth/2+'px';p.style.top=e.clientY-p.offsetHeight/2+'px'});
 p.addEventListener('pointerup',e=>{if(!active)return;active=false;p.classList.remove('dragging');drop(p,e.clientX,e.clientY)})}
 function drop(p,x,y){let best=null,dist=Infinity;document.querySelectorAll('.target:not(.filled)').forEach(t=>{const r=t.getBoundingClientRect(),d=Math.hypot(x-(r.left+r.width/2),y-(r.top+r.height/2));if(d<dist){dist=d;best=t}});if(best&&dist<70){const r=best.getBoundingClientRect();p.style.left=r.left+(r.width-p.offsetWidth)/2+'px';p.style.top=r.top+(r.height-p.offsetHeight)/2+'px';p.style.transform=`rotate(${best.dataset.i*45}deg)`;p.classList.add('placed');best.classList.add('filled');placed++;$('#game-hint').textContent=placed===total?'La flor está completa.':'Te faltan '+(total-placed)+' pétalos';showPhrase();if(placed===total)setTimeout(complete,900)}else{p.style.position='absolute';p.style.left=(12+Math.random()*75)+'%';p.style.top=(68+Math.random()*25)+'%';p.style.transform=`rotate(${Math.random()*50-25}deg)`}}
}
function showPhrase(){const el=$('#game-phrase');el.textContent=CONFIG.petalPhrases[phraseIndex++%CONFIG.petalPhrases.length];el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1900)}
function complete(){go(screens.game,screens.completed)}
let storyIndex=0;$('#btn-story').addEventListener('click',()=>{go(screens.completed,screens.story);showStory()});$('#btn-next-story').addEventListener('click',()=>{storyIndex++;if(storyIndex>=CONFIG.storyTimeline.length){go(screens.story,screens.outro);playOutro()}else showStory()});
function showStory(){const card=$('#story-card');card.classList.remove('visible');setTimeout(()=>{$('#story-text').textContent=CONFIG.storyTimeline[storyIndex];$('#story-number').textContent=String(storyIndex+1).padStart(2,'0');$('#story-progress').style.setProperty('--progress',((storyIndex+1)/CONFIG.storyTimeline.length*100)+'%');$('#btn-next-story').innerHTML=storyIndex===CONFIG.storyTimeline.length-1?'Ver la sorpresa <span>→</span>':'Siguiente <span>→</span>';card.classList.add('visible')},220)}
function playOutro(){setTimeout(()=>$('#outro-1').classList.add('visible'),500);setTimeout(()=>{generateField();$('#outro-2').classList.add('visible')},1900);setTimeout(()=>{$('#outro-3').classList.add('visible');$('#outro-4').classList.add('visible');$('.spotify-final').classList.add('visible')},3300)}
function generateField(){const field=$('#field-container');for(let i=0;i<38;i++)setTimeout(()=>{const f=document.createElement('i');f.className='mini-flower';f.style.left=Math.random()*96+'%';f.style.top=35+Math.random()*58+'%';f.style.transform=`scale(${.55+Math.random()*.8})`;field.append(f);requestAnimationFrame(()=>f.classList.add('bloom'))},i*55)}
