const CONFIG={
  petalPhrases:['Un pétalo para iluminar tu día.','Porque contigo todo se siente más bonito.','Este detalle lleva un poquito de mi cariño.','Me encanta compartir momentos contigo.','Te mereces flores y cosas bonitas siempre.','Gracias por hacerme sonreír.','Eres alguien muy especial para mí.','La flor está completa, pero el cariño sigue creciendo.'],
  storyTimeline:['Quería regalarte flores, pero también quería que este detalle tuviera algo de ti.','Por eso puedes armarla pétalo a pétalo, con calma y sin prisa.','Cada pétalo representa una razón por la que eres especial para mí.','Ojalá esta pequeña flor te acompañe y te saque una sonrisa.','Gracias por estar en mi vida, Poncho.']
};
const $=s=>document.querySelector(s);const screens={intro:$('#screen-intro'),game:$('#screen-game'),completed:$('#screen-completed'),story:$('#screen-story'),outro:$('#screen-outro')};
function go(from,to){from.classList.remove('active');window.setTimeout(()=>to.classList.add('active'),220)}
for(let i=0;i<18;i++){const d=document.createElement('i');d.className='dust';d.style.left=Math.random()*100+'%';d.style.animationDelay=Math.random()*8+'s';$('#ambient').append(d)}
$('#btn-start').addEventListener('click',()=>{go(screens.intro,screens.game);initGame()});
let placed=0,total=8,phraseIndex=0,gameReady=false;
function initGame(){if(gameReady)return;gameReady=true;const board=$('#game-board'),targetBox=$('#targets'),petalBox=$('#petals-container');
 const angles=[-90,-45,0,45,90,135,180,225];
 const center=()=>({x:board.clientWidth/2,y:Math.min(150,board.clientHeight*.34)});
 function paintTargets(){const c=center();targetBox.innerHTML='';angles.forEach((angle,i)=>{const r=angle*Math.PI/180,t=document.createElement('div');t.className='target';t.dataset.i=i;t.style.left=`${c.x+Math.cos(r)*91}px`;t.style.top=`${c.y+Math.sin(r)*91}px`;t.style.transform=`translate(-50%,-50%) rotate(${angle+90}deg)`;targetBox.append(t)})}
 paintTargets();window.addEventListener('resize',paintTargets);
 for(let i=0;i<total;i++){const p=document.createElement('button');p.className='petal';p.dataset.i=i;p.setAttribute('aria-label',`Pétalo ${i+1}`);p.style.left=`${12+(i%4)*24+Math.random()*4}%`;p.style.top=`${72+Math.floor(i/4)*13}%`;p.style.transform=`rotate(${[-12,8,20,-8,12,-18,4,16][i]}deg)`;petalBox.append(p);drag(p)}
 function drag(p){let active=false;p.addEventListener('pointerdown',e=>{if(p.classList.contains('placed'))return;active=true;p.setPointerCapture(e.pointerId);p.classList.add('dragging');const r=p.getBoundingClientRect();p.style.position='fixed';p.style.left=`${r.left}px`;p.style.top=`${r.top}px`;p.style.transform='rotate(0deg)'})
 p.addEventListener('pointermove',e=>{if(active){p.style.left=`${e.clientX-p.offsetWidth/2}px`;p.style.top=`${e.clientY-p.offsetHeight/2}px`}});
 p.addEventListener('pointerup',e=>{if(!active)return;active=false;p.classList.remove('dragging');drop(p,e.clientX,e.clientY)})}
 function reset(p){p.style.position='absolute';p.style.left=`${12+Math.random()*74}%`;p.style.top=`${70+Math.random()*24}%`;p.style.transform=`rotate(${Math.random()*36-18}deg)`}
 function drop(p,x,y){let best=null,dist=Infinity;targetBox.querySelectorAll('.target:not(.filled)').forEach(t=>{const r=t.getBoundingClientRect(),d=Math.hypot(x-(r.left+r.width/2),y-(r.top+r.height/2));if(d<dist){dist=d;best=t}});if(!best||dist>72){reset(p);return}const r=best.getBoundingClientRect();p.style.position='fixed';p.style.left=`${r.left+(r.width-p.offsetWidth)/2}px`;p.style.top=`${r.top+(r.height-p.offsetHeight)/2}px`;p.style.transform=`rotate(${best.dataset.i*45}deg)`;p.classList.add('placed');best.classList.add('filled');placed++;$('#game-hint').textContent=placed===total?'¡Tu flor quedó completa!':`Te faltan ${total-placed} pétalos`;showPhrase();if(placed===total)window.setTimeout(()=>complete(),900)}
}
function showPhrase(){const el=$('#game-phrase');el.textContent=CONFIG.petalPhrases[phraseIndex++%CONFIG.petalPhrases.length];el.classList.add('show');window.setTimeout(()=>el.classList.remove('show'),1900)}
function complete(){go(screens.game,screens.completed)}
let storyIndex=0;$('#btn-story').addEventListener('click',()=>{go(screens.completed,screens.story);showStory()});$('#btn-next-story').addEventListener('click',()=>{storyIndex++;if(storyIndex>=CONFIG.storyTimeline.length){go(screens.story,screens.outro);playOutro()}else showStory()});
function showStory(){const card=$('#story-card');card.classList.remove('visible');window.setTimeout(()=>{$('#story-text').textContent=CONFIG.storyTimeline[storyIndex];$('#story-number').textContent=String(storyIndex+1).padStart(2,'0');$('#story-progress').style.setProperty('--progress',`${(storyIndex+1)/CONFIG.storyTimeline.length*100}%`);$('#btn-next-story').innerHTML=storyIndex===CONFIG.storyTimeline.length-1?'Ver la sorpresa <span>→</span>':'Siguiente <span>→</span>';card.classList.add('visible')},220)}
function playOutro(){window.setTimeout(()=>$('#outro-1').classList.add('visible'),500);window.setTimeout(()=>{generateField();$('#outro-2').classList.add('visible')},1900);window.setTimeout(()=>{$('#outro-3').classList.add('visible');$('#outro-4').classList.add('visible');$('.spotify-final').classList.add('visible')},3300)}
function generateField(){const field=$('#field-container');field.innerHTML='';for(let i=0;i<38;i++)window.setTimeout(()=>{const f=document.createElement('i');f.className='mini-flower';f.style.left=Math.random()*96+'%';f.style.top=35+Math.random()*58+'%';f.style.transform=`scale(${.55+Math.random()*.8})`;field.append(f);requestAnimationFrame(()=>f.classList.add('bloom'))},i*55)}
