/* =====================================================
   PERSONALIZA AQUÍ: cambia frases y recuerdos sin tocar el resto.
   ===================================================== */
const CONFIG={
  petalPhrases:['Porque me haces sonreír.','Porque me encanta conocerte.','Porque contigo todo se siente diferente.','Porque quería hacerte algo solamente a ti.','Porque hasta los días normales se sienten bonitos contigo.','Porque te quiero, Poncho.'],
  storyTimeline:['Antes de conocerte…','No sabía que iba a terminar haciendo esto a estas horas JAJA.','Después apareciste tú…','Y sin darme cuenta, nuestras conversaciones se volvieron de mis partes favoritas del día.','Quería darte un detalle que se sintiera nuestro: sencillo, amarillo y hecho con mucho cariño.','Gracias por existir tan bonito en mi vida, Poncho.']
};
const $=s=>document.querySelector(s);const screens={intro:$('#screen-intro'),game:$('#screen-game'),completed:$('#screen-completed'),story:$('#screen-story'),outro:$('#screen-outro')};
const music=$('#bg-music'),musicBtn=$('#music-btn');let playing=false;
// Los navegadores necesitan una acción del usuario para iniciar audio. Este botón también abre el audio local.
musicBtn.addEventListener('click',async()=>{try{if(playing){music.pause();playing=false;musicBtn.classList.remove('playing')}else{await music.play();playing=true;musicBtn.classList.add('playing')}}catch(e){alert('Añade tu archivo canción.mp3 en la carpeta del proyecto para activar la música.')}});
for(let i=0;i<22;i++){const d=document.createElement('i');d.className='dust';d.style.left=Math.random()*100+'%';d.style.animationDelay=Math.random()*9+'s';d.style.animationDuration=7+Math.random()*8+'s';$('#ambient').append(d)}
function go(from,to){from.classList.remove('active');setTimeout(()=>to.classList.add('active'),120)}
$('#btn-start').addEventListener('click',()=>{go(screens.intro,screens.game);initGame()});
let placed=0,total=6,petals=[],targets=[],phraseIndex=0,gameReady=false;
function initGame(){if(gameReady)return;gameReady=true;const board=$('#game-board'),targetBox=$('#targets'),petalBox=$('#petals-container');
  const center=()=>({x:board.clientWidth/2,y:Math.min(145,board.clientHeight*.32)});const angles=[-90,-30,30,90,150,210];
  function paintTargets(){const c=center();targetBox.innerHTML='';targets=[];angles.forEach((a,i)=>{const rad=a*Math.PI/180,r=71,t=document.createElement('div');t.className='target';t.dataset.i=i;t.style.left=c.x+Math.cos(rad)*r+'px';t.style.top=c.y+Math.sin(rad)*r+'px';t.style.transform=`rotate(${a+90}deg)`;targetBox.append(t);targets.push(t)})}
  paintTargets();window.addEventListener('resize',paintTargets);
  for(let i=0;i<total;i++){const p=document.createElement('button');p.className='petal';p.setAttribute('aria-label','Pétalo '+(i+1));p.dataset.i=i;const col=i%3,row=Math.floor(i/3);p.style.left=(18+col*32+Math.random()*7)+'%';p.style.top=(68+row*16)+'%';p.style.transform=`rotate(${[-16,8,20,-12,5,17][i]}deg)`;petalBox.append(p);petals.push(p);drag(p)}
  function drag(p){let active=false,start={x:0,y:0},origin={x:0,y:0};p.addEventListener('pointerdown',e=>{if(p.classList.contains('placed'))return;active=true;p.setPointerCapture(e.pointerId);p.classList.add('dragging');const r=p.getBoundingClientRect();start={x:e.clientX,y:e.clientY};origin={x:r.left+ r.width/2,y:r.top+r.height/2};p.style.position='fixed';p.style.left=origin.x-r.width/2+'px';p.style.top=origin.y-r.height/2+'px';p.style.transform='rotate(0) scale(1.08)'});p.addEventListener('pointermove',e=>{if(!active)return;p.style.left=origin.x+(e.clientX-start.x)-p.offsetWidth/2+'px';p.style.top=origin.y+(e.clientY-start.y)-p.offsetHeight/2+'px'});p.addEventListener('pointerup',e=>{if(!active)return;active=false;p.classList.remove('dragging');p.releasePointerCapture(e.pointerId);drop(p,e.clientX,e.clientY)})}
  function drop(p,x,y){const boardRect=board.getBoundingClientRect();let best=null,bestDist=Infinity;targets.forEach(t=>{if(t.classList.contains('filled'))return;const r=t.getBoundingClientRect(),d=Math.hypot(x-(r.left+r.width/2),y-(r.top+r.height/2));if(d<bestDist){bestDist=d;best=t}});if(best&&bestDist<92){const r=best.getBoundingClientRect();p.style.position='fixed';p.style.left=r.left+(r.width-p.offsetWidth)/2+'px';p.style.top=r.top+(r.height-p.offsetHeight)/2+'px';p.style.transform=`rotate(${best.style.transform.match(/-?\d+/)?.[0]||0}deg)`;p.classList.add('placed');best.classList.add('filled');placed++;$('#game-hint').textContent=placed===total?'La flor está completa.':'Te faltan '+(total-placed)+' pétalos';showPhrase();if(placed===total)setTimeout(complete,1100)}else{p.style.position='absolute';p.style.left=(12+Math.random()*75)+'%';p.style.top=(69+Math.random()*22)+'%';p.style.transform='rotate('+(Math.random()*36-18)+'deg)'}}
}
function showPhrase(){const el=$('#game-phrase');el.textContent=CONFIG.petalPhrases[phraseIndex++%CONFIG.petalPhrases.length];el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1900)}
function complete(){for(let i=0;i<22;i++){const d=document.createElement('i');d.className='dust';d.style.left=45+Math.random()*10+'%';d.style.animationDelay=i*35+'ms';d.style.animationDuration='2s';$('#game-board').append(d)}go(screens.game,screens.completed)}
let storyIndex=0;$('#btn-story').addEventListener('click',()=>{go(screens.completed,screens.story);showStory()});$('#btn-next-story').addEventListener('click',()=>{storyIndex++;if(storyIndex>=CONFIG.storyTimeline.length){go(screens.story,screens.outro);playOutro()}else showStory()});
function showStory(){const card=$('#story-card');card.classList.remove('visible');setTimeout(()=>{$('#story-text').textContent=CONFIG.storyTimeline[storyIndex];$('#story-number').textContent=String(storyIndex+1).padStart(2,'0');$('.story-progress').style.setProperty('--progress',((storyIndex+1)/CONFIG.storyTimeline.length*100)+'%');$('#btn-next-story').innerHTML=storyIndex===CONFIG.storyTimeline.length-1?'Ver la sorpresa <span>→</span>':'Siguiente <span>→</span>';card.classList.add('visible')},300)}
function playOutro(){setTimeout(()=>$('#outro-1').classList.add('visible'),700);setTimeout(()=>{generateField();$('#outro-2').classList.add('visible')},2800);setTimeout(()=>{$('#outro-3').classList.add('visible');$('#outro-4').classList.add('visible');$('.music-links').classList.add('visible')},4800)}
function generateField(){const field=$('#field-container');for(let i=0;i<42;i++)setTimeout(()=>{const f=document.createElement('i');f.className='mini-flower';f.style.left=Math.random()*96+'%';f.style.top=38+Math.random()*58+'%';f.style.transform=`scale(${.55+Math.random()*.9})`;field.append(f);requestAnimationFrame(()=>f.classList.add('bloom'))},i*65)}
